"""scaffold.py — Skill scaffold writer for the Vessal CLI."""
from __future__ import annotations

from pathlib import Path

_DEFAULT_DESCRIPTION = "(functional description, ≤15 words)"


def write_skill_scaffold(
    base: Path,
    skill_name: str,
    *,
    with_tutorial: bool = True,
    with_ui: bool = True,
    with_server: bool = True,
) -> None:
    """Write a Skill scaffold into `base`.

    Emits __init__.py, skill.py, SKILL.md, requirements.txt, tests/. Optionally
    emits TUTORIAL.md / ui/index.html / server.py based on flags.
    """
    class_name = "".join(part.capitalize() for part in skill_name.split("_"))
    (base / "tests").mkdir(parents=True, exist_ok=True)

    (base / "__init__.py").write_text(
        f'"""{skill_name} — {_DEFAULT_DESCRIPTION}"""\n'
        f'from .skill import {class_name} as Skill\n\n'
        f'__all__ = ["Skill"]\n',
        encoding="utf-8",
    )

    (base / "skill.py").write_text(
        f'"""skill.py — {skill_name} Skill implementation.\n'
        f'\n'
        f'A Skill has two sides:\n'
        f'  Cell side (this file) — tools the Agent calls, signals the Agent reads.\n'
        f'  Hull side (server.py)  — HTTP server that runs outside the frame loop.\n'
        f'\n'
        f'The two sides communicate through shared mutable objects (queue.Queue,\n'
        f'dict) passed at construction time. They do NOT share self.\n'
        f'"""\n'
        f'from __future__ import annotations\n'
        f'\n'
        f'import queue\n'
        f'\n'
        f'from vessal.skills._base import BaseSkill\n'
        f'\n'
        f'\n'
        f'class {class_name}(BaseSkill):\n'
        f'    # name        — unique identifier used to load / reference this Skill.\n'
        f'    # description — ≤15 words, shown by skills.list_skills().\n'
        f'    # tools       — whitelist of Agent-callable methods; anything not\n'
        f'    #               listed here is an internal helper invisible to the Agent.\n'
        f'    name = "{skill_name}"\n'
        f'    description = "{_DEFAULT_DESCRIPTION}"\n'
        f'    tools = ["greet"]\n'
        f'\n'
        f'    def __init__(self, ns=None):\n'
        f'        super().__init__()\n'
        f'        self._ns = ns  # Agent namespace — read/write Agent state here if needed.\n'
        f'\n'
        f'        # _inbox — server.py pushes messages here; the Agent reads them via\n'
        f'        # tool methods. Pass this queue to your Server so both sides share\n'
        f'        # the same object without ever touching each other\'s self.\n'
        f'        self._inbox: queue.Queue[str] = queue.Queue()\n'
        f'\n'
        f'    # ── Tools ──────────────────────────────────────────────────────────────\n'
        f'    # Methods listed in `tools` are auto-discovered by the Kernel and\n'
        f'    # described to the LLM. Every tool MUST produce observable feedback:\n'
        f'    # return a value, print something, or mutate the namespace. Silent\n'
        f'    # success is a bug — the Agent has no way to verify it happened.\n'
        f'\n'
        f'    def greet(self, name: str) -> str:\n'
        f'        """Return a greeting for `name`. Replace with your own methods."""\n'
        f'        return f"Hello, {{name}}!"\n'
        f'\n'
        f'    # ── Signal ─────────────────────────────────────────────────────────────\n'
        f'    # signal_update() is called by the Kernel before every Ping is rendered.\n'
        f'    # It writes to self.signal (a dict). The Kernel reads self.signal to build\n'
        f'    # the named section in the Agent\'s context window:\n'
        f'    #\n'
        f'    #   ══════ {skill_name} ══════\n'
        f'    #   unread: 3\n'
        f'    #\n'
        f'    # Rules:\n'
        f'    #   • Must not raise — called every frame.\n'
        f'    #   • State summaries only — never expose method signatures here.\n'
        f'    #   • Set self.signal = {{}} to emit nothing (section disappears from the Ping).\n'
        f'\n'
        f'    def signal_update(self) -> None:\n'
        f'        pending = self._inbox.qsize()\n'
        f'        self.signal = {{"unread": pending}} if pending else {{}}\n',
        encoding="utf-8",
    )

    (base / "SKILL.md").write_text(
        f'---\n'
        f'name: {skill_name}\n'
        f'version: "0.1.0"\n'
        f'description: "{_DEFAULT_DESCRIPTION}"\n'
        f'author: ""\n'
        f'license: "Apache-2.0"\n'
        f'requires:\n'
        f'  skills: []\n'
        f'---\n'
        f'\n'
        f'# {skill_name}\n'
        f'\n'
        f'> The Agent reads this file on demand via `skills.query_guide("{skill_name}")`.\n'
        f'> It is **not** injected into the system prompt automatically.\n'
        f'> Write it so that after reading this page the Agent can call every method\n'
        f'> without consulting any other source.\n'
        f'\n'
        f'(Replace this paragraph with 1–3 sentences: what the Skill does and when to use it.)\n'
        f'\n'
        f'## Methods\n'
        f'\n'
        f'List each public method with its exact signature and a one-line purpose.\n'
        f'This is the only place the Agent will look for method signatures.\n'
        f'\n'
        f'    greet(name: str) -> str    # Return "Hello, <name>!"\n'
        f'\n'
        f'## Protocol conventions\n'
        f'\n'
        f'These rules are invariants of the Vessal Skill protocol. Violating any is a bug.\n'
        f'\n'
        f'1. `description` ≤15 words — describes function, not method names.\n'
        f'2. `signal_update()` shows state only — never put method signatures there.\n'
        f'3. This file (SKILL.md) is the single source of truth for method signatures.\n'
        f'4. `_prompt()` contains behavior rules only — never the API.\n'
        f'5. Any attribute without a leading `_` is Agent-visible. Guard helpers with `_`.\n'
        f'\n'
        f'## Common pitfalls\n'
        f'\n'
        f'- Putting method names in `signal_update()` or `description` — they belong here.\n'
        f'- Raising exceptions inside `signal_update()` — it must not raise (called every frame).\n'
        f'- Returning nothing from a tool — the Agent needs observable feedback to continue.\n',
        encoding="utf-8",
    )

    (base / "requirements.txt").write_text("", encoding="utf-8")
    (base / "tests" / "__init__.py").write_text("", encoding="utf-8")
    (base / "tests" / f"test_{skill_name}.py").write_text(
        f'"""Tests for the {skill_name} Skill.\n'
        f'\n'
        f'Run with: vessal skill check . --test\n'
        f'"""\n'
        f'from {skill_name}.skill import {class_name}\n'
        f'\n'
        f'\n'
        f'def test_name_attribute():\n'
        f'    assert {class_name}.name == "{skill_name}"\n'
        f'\n'
        f'\n'
        f'def test_greet_returns_greeting():\n'
        f'    skill = {class_name}()\n'
        f'    assert skill.greet("world") == "Hello, world!"\n'
        f'\n'
        f'\n'
        f'def test_signal_empty_when_inbox_empty():\n'
        f'    # signal_update() must set self.signal = {{}} when there is nothing to report.\n'
        f'    skill = {class_name}()\n'
        f'    skill.signal_update()\n'
        f'    assert skill.signal == {{}}\n',
        encoding="utf-8",
    )

    if with_tutorial:
        (base / "TUTORIAL.md").write_text(
            f'# {skill_name} — Development Guide\n'
            f'\n'
            f'This guide covers the full Vessal Skill mental model.\n'
            f'You do not need to read the whitepaper to build a working Skill.\n'
            f'\n'
            f'---\n'
            f'\n'
            f'## 1. How Vessal runs your Agent\n'
            f'\n'
            f'Vessal runs a loop called SORA: State → Observation → Reasoning → Action.\n'
            f'Each pass through the loop is one **frame**:\n'
            f'\n'
            f'1. The Kernel reads everything in the Agent\'s **namespace** (a live Python dict).\n'
            f'2. The Kernel calls `signal_update()` on every loaded Skill and reads `self.signal`.\n'
            f'3. The Kernel renders a **Ping** — a text snapshot of state + signals + recent\n'
            f'   frame history — and sends it to the LLM.\n'
            f'4. The LLM returns a **Pong**: a reasoning block + a Python code snippet.\n'
            f'5. The Kernel executes the code. The code can call Skill methods, read and\n'
            f'   write the namespace, or call external APIs.\n'
            f'6. The execution result becomes the new observation. The next frame begins.\n'
            f'\n'
            f'Your Skill plugs in at two points:\n'
            f'- **Tools** — Python methods callable in step 5.\n'
            f'- **Signal** — a `signal_update()` method that writes `self.signal` for step 2.\n'
            f'\n'
            f'---\n'
            f'\n'
            f'## 2. The two sides of every Skill\n'
            f'\n'
            f'```\n'
            f'skills/{skill_name}/\n'
            f'    skill.py    ← Cell side.  Runs inside the frame loop.\n'
            f'    server.py   ← Hull side.  Runs outside the frame loop, always on.\n'
            f'```\n'
            f'\n'
            f'**Why the split?** The frame loop sleeps between frames. An HTTP server\n'
            f'cannot sleep — it must handle requests at any time. Putting server logic\n'
            f'inside `skill.py` would cause race conditions between the server thread\n'
            f'and the frame loop writing to the same `self` attributes. Keeping them\n'
            f'separate eliminates the hazard entirely.\n'
            f'\n'
            f'The two sides communicate through explicit, thread-safe channels only:\n'
            f'- Shared mutable objects (`queue.Queue`, `dict`) passed at construction.\n'
            f'- HTTP requests from one side to the other.\n'
            f'- The filesystem.\n'
            f'\n'
            f'They do **not** share `self`.\n'
            f'\n'
            f'---\n'
            f'\n'
            f'## 3. Tools — what the Agent can call\n'
            f'\n'
            f'Methods listed in `tools = [...]` are auto-discovered by the Kernel and\n'
            f'described to the LLM. Methods **not** listed are invisible to the Agent.\n'
            f'\n'
            f'```python\n'
            f'class {class_name}(BaseSkill):\n'
            f'    tools = ["greet", "read_inbox"]   # only these are Agent-callable\n'
            f'```\n'
            f'\n'
            f'Rules:\n'
            f'1. Every tool **must** produce observable feedback — return a value, print\n'
            f'   a result, or mutate the namespace. Silent success is a bug; the Agent\n'
            f'   has no way to confirm the action happened.\n'
            f'2. Use type annotations — the Kernel uses them when describing tools to the LLM.\n'
            f'3. Method signatures belong in `SKILL.md` only (see §5). Do not put them\n'
            f'   in `description` or `signal_update()`.\n'
            f'\n'
            f'---\n'
            f'\n'
            f'## 4. Signal — what the Agent sees every frame\n'
            f'\n'
            f'`signal_update()` is called by the Kernel before every Ping is rendered.\n'
            f'It writes to `self.signal`; the Kernel renders that dict as a named section:\n'
            f'\n'
            f'```\n'
            f'══════ {skill_name} ══════\n'
            f'3 unread messages in inbox\n'
            f'```\n'
            f'\n'
            f'Set `self.signal = {{}}` to emit nothing (section disappears from the Ping).\n'
            f'\n'
            f'Use signals to surface real-time state the Agent should act on: pending\n'
            f'messages, active jobs, current status, resource counts.\n'
            f'\n'
            f'Rules:\n'
            f'- **Must not raise.** Runs every single frame.\n'
            f'- **Summaries only.** Do not put method names or signatures here — the Agent\n'
            f'  reads those from `SKILL.md` on demand, not from signals.\n'
            f'- **Keep it short.** It is injected into every Ping; long signals burn\n'
            f'  context window space on every frame.\n'
            f'\n'
            f'---\n'
            f'\n'
            f'## 5. SKILL.md — the Agent\'s reference manual\n'
            f'\n'
            f'The Agent does **not** automatically receive `SKILL.md`. It reads it on demand:\n'
            f'\n'
            f'```python\n'
            f'skills.query_guide("{skill_name}")\n'
            f'```\n'
            f'\n'
            f'Think of it as a one-page API reference the Agent pulls up the first time\n'
            f'it uses your Skill. Write it so that after reading one page the Agent knows\n'
            f'every callable method and any hard usage rules.\n'
            f'\n'
            f'---\n'
            f'\n'
            f'## 6. server.py — the Hull-side server\n'
            f'\n'
            f'`server.py` runs outside the frame loop. Hull starts it when the Skill is\n'
            f'loaded and stops it when the Skill is unloaded. It can handle HTTP requests,\n'
            f'run timers, consume message queues — anything that needs to run continuously.\n'
            f'\n'
            f'All routes are prefixed automatically: a route `"/inbox"` is reachable\n'
            f'externally at `/skills/{skill_name}/inbox`.\n'
            f'\n'
            f'**When you need a server:**\n'
            f'- You receive input from humans or external systems between frames.\n'
            f'- You are serving a UI (`ui/index.html` calls routes here).\n'
            f'- You run a background job while the Agent sleeps.\n'
            f'\n'
            f'**When you do NOT need a server:**\n'
            f'- Your Skill is purely Agent-driven computation (math, parsing, storage).\n'
            f'- Everything is triggered by the Agent calling tool methods.\n'
            f'\n'
            f'If you do not need a server, delete `server.py`. The Skill loads fine without it.\n'
            f'\n'
            f'---\n'
            f'\n'
            f'## 7. ui/index.html — the Console tab\n'
            f'\n'
            f'If your Skill has a `ui/` directory, the Vessal Console mounts `ui/index.html`\n'
            f'as a named tab (the tab name equals the Skill\'s `name`).\n'
            f'\n'
            f'The UI communicates with `server.py` via `fetch()` to\n'
            f'`/skills/{skill_name}/...`. The full data flow:\n'
            f'\n'
            f'```\n'
            f'Human interacts with the UI\n'
            f'  → fetch("/skills/{skill_name}/<route>")\n'
            f'  → server.py handler runs\n'
            f'  → handler pushes data into the shared queue\n'
            f'  → skill.signal_update() writes self.signal; next Ping picks it up\n'
            f'  → Agent calls a tool method to act on the data\n'
            f'```\n'
            f'\n'
            f'If you do not need a UI, delete the `ui/` directory.\n'
            f'\n'
            f'---\n'
            f'\n'
            f'## 8. Checklist before publishing\n'
            f'\n'
            f'- [ ] `description` ≤15 words; describes function, not method names\n'
            f'- [ ] Every tool method returns a value or prints (no silent success)\n'
            f'- [ ] `signal_update()` sets `self.signal` without raising\n'
            f'- [ ] `SKILL.md` lists every public method with its exact signature\n'
            f'- [ ] Method signatures appear **only** in `SKILL.md`\n'
            f'- [ ] Internal helpers use `_` prefix\n'
            f'- [ ] `tests/test_{skill_name}.py` has at least one non-placeholder test\n'
            f'- [ ] Validate with: `vessal skill check .`\n',
            encoding="utf-8",
        )

    if with_ui:
        ui_dir = base / "ui"
        ui_dir.mkdir(parents=True, exist_ok=True)
        (ui_dir / "index.html").write_text(
            f'<!doctype html>\n'
            f'<!--\n'
            f'  ui/index.html — {skill_name} Skill UI\n'
            f'\n'
            f'  The Vessal Console mounts this file as a tab named "{skill_name}".\n'
            f'  It runs in an iframe next to the chat pane and the Agent frame-state pane.\n'
            f'\n'
            f'  How this page connects to the Agent:\n'
            f'\n'
            f'    This page  →  fetch("/skills/{skill_name}/...")  →  server.py route handler\n'
            f'    server.py  →  shared queue  →  skill.py signal_update() or tool method\n'
            f'    skill.py   →  Agent sees update in next frame Ping\n'
            f'\n'
            f'  To add a new interaction:\n'
            f'    1. Write a handler function in server.py.\n'
            f'    2. Add it to the `routes` list:  ("POST", "/my-route", my_handler)\n'
            f'    3. Call it here with fetch("/skills/{skill_name}/my-route", ...)\n'
            f'-->\n'
            f'<html>\n'
            f'<head>\n'
            f'  <meta charset="utf-8">\n'
            f'  <title>{skill_name}</title>\n'
            f'  <style>\n'
            f'    /* This page lives inside an iframe — size it relative to the viewport. */\n'
            f'    body  {{ font-family: sans-serif; padding: 1.5rem; max-width: 640px; margin: 0; }}\n'
            f'    h2    {{ margin-top: 0; }}\n'
            f'    button {{ padding: .4rem .9rem; cursor: pointer; margin-right: .5rem; }}\n'
            f'    pre   {{ background: #f4f4f4; padding: .8rem; border-radius: 4px;\n'
            f'             white-space: pre-wrap; min-height: 2rem; }}\n'
            f'    .error {{ color: #c00; }}\n'
            f'  </style>\n'
            f'</head>\n'
            f'<body>\n'
            f'  <h2>{skill_name}</h2>\n'
            f'\n'
            f'  <!--\n'
            f'    Example: click a button → call server.py → display the response.\n'
            f'    This demonstrates the full round-trip: UI → server route → display.\n'
            f'    Replace or extend this with your actual interface.\n'
            f'  -->\n'
            f'  <button id="ping-btn">Ping server</button>\n'
            f'  <pre id="output">— waiting —</pre>\n'
            f'\n'
            f'  <script>\n'
            f'    const output = document.getElementById("output");\n'
            f'\n'
            f'    // ── callSkill(path, options?) ───────────────────────────────────────\n'
            f'    // Convenience wrapper. All routes live under /skills/{skill_name}/.\n'
            f'    //\n'
            f'    // GET example:\n'
            f'    //   callSkill("/hello")\n'
            f'    //\n'
            f'    // POST example:\n'
            f'    //   callSkill("/inbox", {{\n'
            f'    //     method: "POST",\n'
            f'    //     headers: {{"Content-Type": "application/json"}},\n'
            f'    //     body: JSON.stringify({{ text: "hello" }})\n'
            f'    //   }})\n'
            f'    async function callSkill(path, options = {{}}) {{\n'
            f'      const resp = await fetch("/skills/{skill_name}" + path, options);\n'
            f'      if (!resp.ok) throw new Error(`HTTP ${{resp.status}} ${{resp.statusText}}`);\n'
            f'      return resp.json();\n'
            f'    }}\n'
            f'\n'
            f'    // ── Example: ping the /hello route ─────────────────────────────────\n'
            f'    // The /hello route is defined in server.py and served at /skills/{skill_name}/hello.\n'
            f'    // This pattern — button click → fetch → display — is the basic building\n'
            f'    // block for every interaction in your UI.\n'
            f'    document.getElementById("ping-btn").addEventListener("click", async () => {{\n'
            f'      output.className = "";\n'
            f'      output.textContent = "…";\n'
            f'      try {{\n'
            f'        const data = await callSkill("/hello");\n'
            f'        output.textContent = JSON.stringify(data, null, 2);\n'
            f'      }} catch (err) {{\n'
            f'        output.className = "error";\n'
            f'        output.textContent = "Error: " + err.message;\n'
            f'      }}\n'
            f'    }});\n'
            f'  </script>\n'
            f'</body>\n'
            f'</html>\n',
            encoding="utf-8",
        )

    if with_server:
        (base / "server.py").write_text(
            f'"""server.py — HTTP routes for the {skill_name} Skill (Hull side).\n'
            f'\n'
            f'This module runs OUTSIDE the Agent\'s frame loop. Hull starts it when the\n'
            f'Skill is loaded and stops it on unload. It can handle HTTP requests, run\n'
            f'timers, or consume message queues — anything that needs to run continuously.\n'
            f'\n'
            f'All routes are automatically prefixed with /skills/{skill_name}/.\n'
            f'Registering "/inbox" here makes it reachable at /skills/{skill_name}/inbox.\n'
            f'\n'
            f'Communicating with skill.py (Cell side)\n'
            f'────────────────────────────────────────\n'
            f'The two sides do NOT share a class instance. Pass a shared mutable object\n'
            f'(queue.Queue, dict) at construction time and read/write it on both sides.\n'
            f'\n'
            f'Pattern — receive a message from a human and surface it to the Agent:\n'
            f'\n'
            f'    # 1. In skill.py __init__, create the shared channel:\n'
            f'    #      self._inbox: queue.Queue[str] = queue.Queue()\n'
            f'    #\n'
            f'    # 2. In this file, push into the same queue via a closure or module var:\n'
            f'    #      def post_inbox(request):\n'
            f'    #          _inbox.put(request.json()["text"])\n'
            f'    #          return {{"status": "queued"}}\n'
            f'    #\n'
            f'    # 3. In skill.py signal_update(), surface the queue depth:\n'
            f'    #      def signal_update(self):\n'
            f'    #          n = self._inbox.qsize()\n'
            f'    #          self.signal = {{"messages": n}} if n else {{}}\n'
            f'    #\n'
            f'    # 4. Add a tool method so the Agent can drain the queue:\n'
            f'    #      def read_inbox(self) -> str | None:\n'
            f'    #          return self._inbox.get_nowait() if not self._inbox.empty() else None\n'
            f'\n'
            f'If you do not need a server, delete this file. The Skill loads fine without it.\n'
            f'"""\n'
            f'from __future__ import annotations\n'
            f'\n'
            f'\n'
            f'def hello(request):\n'
            f'    """Health-check route called by ui/index.html on button click.\n'
            f'\n'
            f'    Every route receives the incoming request object and must return either\n'
            f'    a JSON-serialisable dict or a plain string. Replace this with real logic.\n'
            f'    """\n'
            f'    return {{"status": "ok", "skill": "{skill_name}"}}\n'
            f'\n'
            f'\n'
            f'# ── Route table ────────────────────────────────────────────────────────────\n'
            f'# Format: (HTTP method, path suffix, handler function)\n'
            f'# start() registers each entry with Hull; paths are auto-prefixed with\n'
            f'# /skills/{skill_name}/ by the ScopedHullApi.\n'
            f'_routes = [\n'
            f'    ("GET", "/hello", hello),\n'
            f'    # ("POST", "/inbox", post_inbox),   # uncomment after defining post_inbox\n'
            f']\n'
            f'\n'
            f'\n'
            f'def start(hull_api, skill=None) -> None:\n'
            f'    """Hull entry point — called once when the Skill is loaded.\n'
            f'\n'
            f'    hull_api: ScopedHullApi — use hull_api.register_route(method, path, handler)\n'
            f'              to expose routes. All paths are automatically prefixed with\n'
            f'              /skills/{skill_name}/.\n'
            f'    skill: the Skill instance if you need to share state with skill.py.\n'
            f'    """\n'
            f'    for method, path, handler in _routes:\n'
            f'        hull_api.register_route(method, path, handler)\n',
            encoding="utf-8",
        )
